import "@/common/css/index.css";
import { poppins } from "@/common/css/fonts";

import type { Metadata } from "next";

import { AlertMessage } from "@/alert-message/components";
import { ThemeManager } from "@/theme/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen ${poppins.className}`}>
        {children}
        <AlertMessage />
        <ThemeManager />
      </body>
    </html>
  );
}
